platform :ios, '8.0'
use_frameworks!

#pod 'Alamofire', '~> 3.1.2'
pod 'CSNetManager', '~> 0.0.6'
pod 'MBProgressHUD'
pod 'SnapKit', '~> 0.19.1'
pod 'XMLDictionary'
pod 'SDWebImage'
pod 'RKNotificationHub'